name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pre Check
      run: cargo check --all
    - name: Unit Test
      run: cargo test
    - name: Build
      run: cargo build --verbose --release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: spicy-scarlet-slug
        path: target/release/spicy-scarlet-slug
        retention-days: 1

  test:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3
    - name: Download workflow build
      uses: actions/download-artifact@v3
      with:
        name: spicy-scarlet-slug
    - name: Run service
      run: ./spicy-scarlet-slug &
    - name: Run HTTP tests
      run: hurl --test tests/*hurl
