name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download workflow build
      uses: actions/download-artifact@v3
      with:
        name: spicy-scarlet-slug
    - name: Run service
      run: ./spicy-scarlet-slug &
    - name: Run HTTP tests
      run: hurl --test tests/*hurl
